id: P000363
initial_creation_type: ocr
created_at: 16/03/2020
last_modified_at: 2021-12-16 15:36:02.070621
source_metadata:
  id: bdr:W27491
  title: རྙིང་མའི་རྒྱུད་བཅུ་བདུན།（འབྲུག་བུམ་ཐང་ཐར་པ་གླིང་གི་པར་མ།）
  author: ''
  volumes:
    3edb7e9e1219420b9a3ce450664ee4ba:
      image_group_id: I4447
      title: ''
      volume_number: 1
      total_pages: 746
      base_file: v001.txt
    c0e0385fccee42baac49ce82162ee519:
      image_group_id: I4448
      title: ''
      volume_number: 2
      total_pages: 666
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
