id: I4EB6448B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-16T12:38:54+00:00'
last_modified: '2022-06-10T04:59:42.825251+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27491
  title: རྙིང་མའི་རྒྱུད་བཅུ་བདུན།（འབྲུག་བུམ་ཐང་ཐར་པ་གླིང་གི་པར་མ།）
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C754:
      image_group_id: I4447
      title: ''
      total_pages: 746
      order: 1
      base_file: C754.txt
    6EC4:
      image_group_id: I4448
      title: ''
      total_pages: 666
      order: 2
      base_file: 6EC4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
